export const USERS_SCENE = {
   STARTED: 'USER_STARTED_SCENE',
   ABOUT: 'USER_ABOUT_SCENE',

   MENU: 'USER_MENU_SCENE',
   MENU_GRILL: 'USER_MENU_GRILL_SCENE',
   MENU_COFFEE: 'USER_MENU_COFFEE_SCENE',
   MENU_WEEKLY: 'USER_MENU_WEEKLY_SCENE',
   MENU_WEEKLY2: 'USER_MENU_WEEKLY2_SCENE',
   MENU_DAILY: 'USER_MENU_DAILY_SCENE',

   MENU_GRILL_BREAKFAST: 'MENU_GRILL_BREAKFAST',
   MENU_GRILL_MAIN: 'MENU_GRILL_MAIN',
   MENU_GRILL_GRANISH: 'MENU_GRILL_GRANISH',
   MENU_GRILL_SAUSE: 'MENU_GRILL_SAUSE',

   KBZHU: 'USER_KBZHU_SCENE',
   PROMO: 'USER_PROMO_SCENE',

   CART: 'USER_CART_SCENE',
}